const options = [
  { value: "Acid House", label: "Acid House" },
  { value: "Acid Jazz", label: "Acid Jazz" },
  { value: "Acoustic Blues", label: "Acoustic Blues" },
  { value: "Alternative Rock", label: "Alternative Rock" },
  { value: "Ambient", label: "Ambient" },
  { value: "Black Metal", label: "Black Metal" },
  { value: "Blues", label: "Blues" },
  { value: "Blues Rock", label: "Blues Rock" },
  { value: "Classic Blues", label: "Classic Blues" },
  { value: "Classical", label: "Classical" },
  { value: "Country", label: "Country" },
  { value: "Death Metal", label: "Death Metal" },
  { value: "Deep House", label: "Deep House" },
  { value: "Disco", label: "Disco" },
  { value: "Drum’n’bass", label: "Drum’n’bass" },
  { value: "Dubstep", label: "Dubstep" },
  { value: "Easy Listening", label: "Easy Listening" },
  { value: "Electronica", label: "Electronica" },
  { value: "Experimental Rock", label: "Experimental Rock" },
  { value: "Folk Music", label: "Folk Music" },
  { value: "Funk", label: "Funk" },
  { value: "Garage", label: "Garage" },
  { value: "Grime", label: "Grime" },
  { value: "Grunge", label: "Grunge" },
  { value: "Hard Rock", label: "Hard Rock" },
  { value: "House", label: "House" },
  { value: "Indie Pop", label: "Indie Pop" },
  { value: "Indie Rock", label: "Indie Rock" },
  { value: "Industrial", label: "Industrial" },
  { value: "Jazz", label: "Jazz" },
  { value: "Jungle", label: "Jungle" },
  { value: "Lo-fi", label: "Lo-fi" },
  { value: "Metal", label: "Metal" },
  { value: "Minimal", label: "Minimal" },
  { value: "New Wave", label: "New Wave" },
  { value: "Punk", label: "Punk" },
  { value: "Progressive Rock", label: "Progressive Rock" },
  { value: "Psychedelic Rock", label: "Psychedelic Rock" },
  { value: "Ragtime Blues", label: "Ragtime Blues" },
  { value: "Rock", label: "Rock" },
  { value: "Ska", label: "Ska" },
  { value: "Soul", label: "Soul" },
  { value: "Techno", label: "Techno" },
  { value: "Traditional", label: "Traditional" },
  { value: "Trance", label: "Trance" },
  { value: "Trip Hop", label: "Trip Hop" },
  { value: "World Music", label: "World Music" },
];

export default options;
